### ISSUE TITLE
Add Markdown resources

### ISSUE THREAD

**Issue by elitadanilyuk** [PortfoliU-Project/PortfoliU-Project#1]
- [x] Add these resources in a Markdown.md under Resources. Please go into detail regarding what the resources are about.
   - https://www.markdownguide.org/cheat-sheet/
   - https://lab.github.com/githubtraining/communicating-using-markdown
   - https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
- [x] Add a brief paragraph about why markdown is an important skill to know.
-

**Comment by BrendonLH** [comment]
A fellow classmate and Myself would like to take this on if that is ok?

**Comment by mlh6118** [comment]
> A fellow classmate and Myself would like to take this on if that is ok?

I am the fellow classmate.

**Comment by elitadanilyuk** [comment]
Absolutely, I created Markdown.md with a short blurb, but there is a good bit more that needs done.  Let me push those changes for you and y'all can take it on!
(I'll update y'all as soon as this is done!)

**Comment by BrendonLH** [comment]
> Absolutely, I created Markdown.md with a short blurb, but there is a good bit more that needs done. Let me push those changes for you and y'all can take it on! (I'll update y'all as soon as this is done!)

awesome thank you!

**Comment by elitadanilyuk** [comment]
Okay, that has been pushed. Markdown.md should be under Resources. Let me know if you have any issues!

**Comment by mlh6118** [comment]
Pull request has been made.

**Comment by elitadanilyuk** [comment]
> Pull request has been made.

I left two small comments for clarity. 😃

**Comment by elitadanilyuk** [comment]
PR merged, great work guys!  Thank you!

**Comment by BrendonLH** [comment]
> PR merged, great work guys! Thank you!

👍🏻 👍🏻
