### ISSUE TITLE
Remove Create_and_Host_Webpage_on_Github.md

### ISSUE THREAD

**Issue by elitadanilyuk** [PortfoliU-Project/PortfoliU-Project#13]
Delete Create_and_Host_Webpage_on_Github.md. This file is redundant, as the GitHub Docs guide is easy and straightforward.

- [ ] Delete the Create_and_Host_Webpage_on_Github.md file out of `Resources/Tutorials/`
- [ ] Remove the link to the doc anywhere it exists
   - Known location: `Resources/README.md`

**Comment by Rohit-R2000** [comment]
let me do this mam

**Comment by yash-sharma13** [comment]
I have done it. Please check the pr

**Comment by elitadanilyuk** [comment]
@Rohit-R2000 Thank you for contributing!  If you like the repo, please feel free to star it! 😄 🤩 ⭐
